#!/usr/bin/env python
"""Task tooling for AI Training 06 — read, generate and check.

The design rule behind all of it: **store the forward edge, derive the rest.** A task file's
front-matter is the only place a fact about that task is written down. Everything else — the
child list, the "blocks" list, the index in tasks/README.md — is computed from it. Facts that
are computed cannot drift from facts that are stored.

Commands
--------
  context T-NNN   Everything needed to start work on one task, and nothing else.
                  Replaces reading CLAUDE.md + the brief + the lessons + the index +
                  the task file to find the few hundred bytes that matter.

  index           Regenerate the task tables in tasks/README.md from front-matter.
                  Hand-written sections (open decisions, standards) are preserved.

  check           Validate what is still hand-made: unknown status/phase values, references
                  to tasks that do not exist, dependency cycles, broken markdown links, and
                  (with --closing) a non-empty deliverables/_working/.

Usage
-----
  python tools/tasks/task.py context T-001
  python tools/tasks/task.py index
  python tools/tasks/task.py check [--closing]

Exit code 0 on success, 1 on any problem. Pure standard library, by L-07. Console output is
ASCII — the Windows console mangles em-dashes under cp1252.
"""

import glob
import os
import re
import sys

# The Windows console defaults to cp1252, which mangles accented characters and
# typographic punctuation. Task content is UTF-8, so say so rather than losing characters.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
INDEX = os.path.join("tasks", "README.md")
DECISIONS = os.path.join("tasks", "DECISIONS.md")
WORKING = os.path.join("deliverables", "_working")

BEGIN = "<!-- generated by tools/tasks/task.py - do not edit by hand -->"
END = "<!-- end generated -->"

# The vocabulary. Anything outside these is a typo, and `check` says so.
STATUSES = ["proposed", "specified", "planned", "in_progress", "blocked",
            "review", "done", "cancelled"]
OPEN_STATUSES = [s for s in STATUSES if s not in ("done", "cancelled")]
PHASES = ["specify", "plan", "implement", "review"]

LINK = re.compile(r"\[[^\]]*\]\(([^)#\s]+)(?:#[^)\s]*)?\)")
SCALAR = re.compile(r"^(\w+):[ \t]*(.*?)[ \t]*$", re.M)


def read(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def write(path, text):
    # newline="\n" so output is identical on every platform (L-11).
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)


def parse_list(raw):
    """[T-001, T-002] -> ['T-001', 'T-002']; '' / [] / null -> []."""
    raw = (raw or "").strip()
    if not raw or raw in ("[]", "null", "none", "None"):
        return []
    return [item.strip() for item in raw.strip("[]").split(",") if item.strip()]


class Task(object):
    def __init__(self, path):
        self.path = path.replace("\\", "/")
        self.name = os.path.basename(self.path)
        text = read(path)
        end = text.find("\n---", 3) if text.startswith("---") else -1
        fm = text[3:end] if end != -1 else ""
        self.fields = dict(SCALAR.findall(fm))

        self.id = self.fields.get("id", "")
        self.title = self.fields.get("title", "")
        self.status = self.fields.get("status", "")
        self.phase = self.fields.get("phase", "")
        self.type = self.fields.get("type", "")
        self.wp = self.fields.get("work_package", "none")
        self.owner = self.fields.get("owner", "")

        parent = (self.fields.get("parent") or "").strip()
        self.parent = "" if parent in ("", "null", "none", "None") else parent
        self.blocked_by = parse_list(self.fields.get("blocked_by"))
        self.related = parse_list(self.fields.get("related"))
        self.decisions = parse_list(self.fields.get("decisions"))
        # `deliverables:` is a block list - its items are on the following lines, so it needs
        # the raw front-matter, not the scalar map. Trailing "# comment" is stripped.
        block = re.search(r"^deliverables:[ \t]*\n((?:[ \t]+-.*\n?)*)", fm, re.M)
        self.outputs = [item.split("#")[0].strip()
                        for item in re.findall(r"^[ \t]+-[ \t]*(.+)$", block.group(1), re.M)
                        ] if block else []

        # Derived — never stored.
        self.children = []
        self.blocks = []

    @property
    def is_open(self):
        return self.status in OPEN_STATUSES


def load():
    """Read every task file and wire up the derived (inverse) edges."""
    os.chdir(ROOT)
    tasks = {}
    for path in sorted(glob.glob(os.path.join("tasks", "T-*.md"))):
        t = Task(path)
        if t.id:
            tasks[t.id] = t

    for t in tasks.values():
        if t.parent in tasks:
            tasks[t.parent].children.append(t.id)
        for upstream in t.blocked_by:
            if upstream in tasks:
                tasks[upstream].blocks.append(t.id)
    return tasks


def line(t, tasks):
    """One-line summary of a task, for use inside another task's context."""
    return "%s  %-11s %s" % (t.id, t.status, t.title)


def markdown_files():
    """Every .md in the project, including dot-directories that glob's ** skips."""
    for base, dirs, files in os.walk("."):
        dirs[:] = [d for d in dirs if d not in (".git", "node_modules", "__pycache__")]
        for f in files:
            if f.endswith(".md"):
                yield os.path.normpath(os.path.join(base, f))


def load_decisions():
    """Parse the D-NNN rows out of tasks/DECISIONS.md. That table is the source; which
    tasks a decision blocks is derived from the tasks' `decisions:` fields."""
    register = {}
    if not os.path.exists(DECISIONS):
        return register
    for ln in read(DECISIONS).splitlines():
        if not ln.startswith("| D-"):
            continue
        cells = [c.strip() for c in ln.strip("|").split("|")]
        if len(cells) >= 4:
            register[cells[0]] = {"id": cells[0], "status": cells[1],
                                  "owner": cells[2], "question": cells[3],
                                  "blocks": []}
    return register


# --------------------------------------------------------------------------- context

def cmd_context(args):
    if not args:
        print("usage: task.py context T-NNN")
        return 1
    wanted = args[0].upper()
    tasks = load()
    if wanted not in tasks:
        print("No such task: %s" % wanted)
        return 1

    t = tasks[wanted]
    out = []
    out.append("=" * 72)
    out.append("%s  %s" % (t.id, t.title))
    out.append("=" * 72)
    out.append("status %s | phase %s | type %s | wp %s | owner %s"
               % (t.status, t.phase, t.type, t.wp, t.owner))
    out.append("file   %s" % t.path)

    blockers = [tasks[b] for b in t.blocked_by if b in tasks]
    open_blockers = [b for b in blockers if b.is_open]
    if blockers:
        out.append("")
        out.append("BLOCKED BY  (must land first)")
        for b in blockers:
            flag = "  <-- still open" if b.is_open else ""
            out.append("  " + line(b, tasks) + flag)

    if t.blocks:
        out.append("")
        out.append("BLOCKS  (waiting on this one)")
        for b in t.blocks:
            out.append("  " + line(tasks[b], tasks))

    if t.parent and t.parent in tasks:
        out.append("")
        out.append("PARENT")
        out.append("  " + line(tasks[t.parent], tasks))

    if t.children:
        out.append("")
        out.append("CHILDREN")
        for c in t.children:
            out.append("  " + line(tasks[c], tasks))

    if t.related:
        out.append("")
        out.append("RELATED  (context, not a dependency)")
        for r in t.related:
            if r in tasks:
                out.append("  " + line(tasks[r], tasks))

    register = load_decisions()
    linked = [register[d] for d in t.decisions if d in register]
    open_decisions = [d for d in linked if d["status"] != "closed"]
    if linked:
        out.append("")
        out.append("DECISIONS  (%s)" % DECISIONS)
        for d in linked:
            flag = "  <-- UNANSWERED" if d["status"] != "closed" else ""
            out.append("  %s %-7s %s%s"
                       % (d["id"], d["status"], d["question"][:70], flag))

    if t.outputs:
        out.append("")
        out.append("PRODUCES")
        for path in t.outputs:
            out.append("  [%s] %s" % ("x" if os.path.exists(path) else " ", path))

    out.append("")
    if open_blockers:
        out.append("NEXT: blocked - clear %s first."
                   % ", ".join(b.id for b in open_blockers))
    elif open_decisions:
        out.append("NEXT: needs a decision from %s - %s."
                   % (open_decisions[0]["owner"],
                      ", ".join(d["id"] for d in open_decisions)))
    else:
        out.append("NEXT: read the file above, then work the '%s' phase." % t.phase)
    out.append("Rules: tasks/TASK-WORKFLOW.md   Lessons: docs/LESSONS.md")

    print("\n".join(out))
    return 0


# --------------------------------------------------------------------------- index

def table(rows, header):
    out = [header, "| " + " | ".join([":---"] * header.count("|") and
                                      [":---"] * (header.count("|") - 1)) + " |"]
    # Rebuild the separator to match the header's column count exactly.
    cols = header.count("|") - 1
    out[1] = "|" + "|".join([" :--- "] * cols) + "|"
    out.extend(rows)
    return out


def cmd_index(args):
    tasks = load()
    ordered = sorted(tasks.values(), key=lambda t: t.id)

    active, closed = [], []
    for t in ordered:
        link = "[%s](%s)" % (t.id, t.name)
        if t.is_open:
            blockers = ", ".join(b for b in t.blocked_by
                                 if b in tasks and tasks[b].is_open) or "-"
            downstream = ", ".join(t.blocks) or "-"
            active.append("| %s | %s | %s | `%s` | %s | %s | %s |"
                          % (link, t.title, t.wp, t.status, t.phase,
                             blockers, downstream))
        else:
            closed.append("| %s | %s | `%s` | %s |"
                          % (link, t.title, t.status,
                             t.fields.get("updated", "")))

    nxt = max(int(t.id.split("-")[1]) for t in ordered) + 1

    block = [BEGIN, ""]
    block.append("## Active")
    block.append("")
    if active:
        block.append("| ID | Title | WP | Status | Phase | Blocked by | Blocks |")
        block.append("| :--- | :--- | :---: | :--- | :--- | :--- | :--- |")
        block.extend(active)
    else:
        block.append("_None._")
    block.append("")
    block.append("## Closed")
    block.append("")
    block.append("| ID | Title | Status | Updated |")
    block.append("| :--- | :--- | :--- | :--- |")
    block.extend(closed)
    block.append("")
    block.append("## Next ID")
    block.append("")
    block.append("`T-%03d`" % nxt)
    block.append("")
    block.append(END)

    text = read(INDEX)
    generated = "\n".join(block)
    if BEGIN in text and END in text:
        head = text[:text.index(BEGIN)]
        tail = text[text.index(END) + len(END):]
        text = head + generated + tail
    else:
        text = text.rstrip() + "\n\n" + generated + "\n"
    write(INDEX, text)
    print("Regenerated %s - %d active, %d closed, next T-%03d"
          % (INDEX, len(active), len(closed), nxt))
    return 0


# --------------------------------------------------------------------------- check

def cmd_check(args):
    closing = "--closing" in args
    tasks = load()
    register = load_decisions()
    problems, warnings = [], []

    for t in sorted(tasks.values(), key=lambda x: x.id):
        if t.status not in STATUSES:
            problems.append("BAD STATUS   %s has `%s`; allowed: %s"
                            % (t.id, t.status, ", ".join(STATUSES)))
        if t.phase not in PHASES:
            problems.append("BAD PHASE    %s has `%s`; allowed: %s"
                            % (t.id, t.phase, ", ".join(PHASES)))
        if "children" in t.fields:
            problems.append("STALE FIELD  %s still has `children:` - it is derived from "
                            "`parent:` now; remove it" % t.id)
        for ref, field in ([(t.parent, "parent")] if t.parent else []) + \
                          [(r, "blocked_by") for r in t.blocked_by] + \
                          [(r, "related") for r in t.related]:
            if ref not in tasks:
                problems.append("DANGLING     %s.%s -> %s does not exist"
                                % (t.id, field, ref))
        if t.status == "blocked" and not t.blocked_by:
            problems.append("NO BLOCKER   %s is `blocked` with an empty `blocked_by`" % t.id)
        for d in t.decisions:
            if d not in register:
                problems.append("DANGLING     %s.decisions -> %s is not in %s"
                                % (t.id, d, DECISIONS))

    # A blocks B blocks A would deadlock the backlog silently.
    seen, stack = set(), set()

    def walk(tid):
        if tid in stack:
            problems.append("CYCLE        dependency loop through %s" % tid)
            return
        if tid in seen or tid not in tasks:
            return
        stack.add(tid)
        for up in tasks[tid].blocked_by:
            walk(up)
        stack.discard(tid)
        seen.add(tid)

    for tid in sorted(tasks):
        walk(tid)

    # glob's ** skips dot-directories, which hid .handoff/ and .claude/ - and .handoff/HANDOFF.md
    # is the live resume pointer, the one file where a broken link costs the most. Walk instead.
    for md in sorted(markdown_files()):
        base = os.path.dirname(md)
        for m in LINK.finditer(read(md)):
            target = m.group(1)
            if target.startswith(("http://", "https://", "mailto:")):
                continue
            if not os.path.exists(os.path.normpath(os.path.join(base, target))):
                problems.append("BROKEN LINK  %s -> %s" % (md, target))

    leftovers = os.listdir(WORKING) if os.path.isdir(WORKING) else []
    if leftovers:
        msg = "%s not empty: %s" % (WORKING, ", ".join(sorted(leftovers)))
        (problems if closing else warnings).append(
            ("NOT EMPTY    " if closing else "note: ") + msg)

    for w in warnings:
        print(w)
    if problems:
        print("\nFAIL - %d problem(s):\n" % len(problems))
        for p in problems:
            print("  " + p)
        return 1
    print("OK - %d tasks, vocabulary valid, references resolve, 0 broken links"
          % len(tasks))
    return 0


def cmd_decisions(args):
    """Every decision, and - derived from the tasks - what it is holding up."""
    tasks = load()
    register = load_decisions()
    for t in tasks.values():
        for d in t.decisions:
            if d in register and t.is_open:
                register[d]["blocks"].append(t.id)

    if not register:
        print("No decisions register at %s" % DECISIONS)
        return 1
    for d in sorted(register.values(), key=lambda x: x["id"]):
        held = ", ".join(sorted(d["blocks"])) or "-"
        mark = " " if d["status"] == "closed" else "!"
        print("%s %s  %-7s  owner %-6s  blocks %s"
              % (mark, d["id"], d["status"], d["owner"], held))
        print("    %s" % d["question"])
    unanswered = [d for d in register.values() if d["status"] != "closed" and d["blocks"]]
    print("\n%d decision(s) currently holding up open work." % len(unanswered))
    return 0


def cmd_deliverables(args):
    """What every task declares it produces, and whether it exists yet. Derived - there is
    no deliverable list to maintain."""
    tasks = load()
    rows, missing = [], 0
    for t in sorted(tasks.values(), key=lambda x: (x.wp, x.id)):
        for path in t.outputs:
            there = os.path.exists(path)
            missing += 0 if there else 1
            rows.append((t.wp, t.id, t.status, "x" if there else " ", path))
    if not rows:
        print("No task declares any deliverables.")
        return 0
    print("%-5s %-6s %-11s %s  %s" % ("WP", "TASK", "STATUS", "?", "PATH"))
    for wp, tid, status, mark, path in rows:
        print("%-5s %-6s %-11s [%s] %s" % (wp, tid, status, mark, path))
    print("\n%d declared output(s); %d not on disk yet." % (len(rows), missing))
    return 0


COMMANDS = {"context": cmd_context, "index": cmd_index, "check": cmd_check,
            "decisions": cmd_decisions, "deliverables": cmd_deliverables}


def main():
    argv = sys.argv[1:]
    if not argv or argv[0] not in COMMANDS:
        print(__doc__.split("Usage")[1].strip() if "Usage" in __doc__ else "")
        print("commands: " + ", ".join(sorted(COMMANDS)))
        return 1
    os.chdir(ROOT)
    return COMMANDS[argv[0]](argv[1:])


if __name__ == "__main__":
    sys.exit(main())
